### ISSUE TITLE
유저인터뷰 정리

### ISSUE THREAD

**Issue by Bookbla0** [BookBLA/espresso#2]
# 유저인터뷰 정리 11월 8일
---
이름 : 홍두원

**Comment by Bookbla0** [comment]
https://www.notion.so/09913d7d1351426ab5eba688f0fa3240?pvs=4

**Comment by leevigong** [comment]
엽서 거절되면 보낸 사람한테 책갈피 돌려주는걸 알려주면 좋을 거같습니다..!

**Comment by Bookbla0** [comment]
> 엽서 거절되면 보낸 사람한테 책갈피 돌려주는걸 알려주면 좋을 거같습니다..!

어떤 식으로 알려줄지 좀 고민해봐야겠군요. 이게 앱에서 맨날 거절 됐다고 뜨는게 유저들한테 좋지는 않아가지고.
유저들이 엽서를 여러개 보내고 그 중에 한 두개만 수락되가지고 채팅하는거일텐데
